openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vlfkalem1@
    url: jdbc:mysql://52.73.138.41:3306/dream_tree
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp